<AppBox>:
  BoxLayout:
    orientation: 'horizontal'
    BoxLayout:
      orientation: 'vertical'
      Slider:
        orientation: "vertical"
        size_hint_y: 0.7        
      Label:
        size_hint_y: 0.3
        text: 'Left'
    BoxLayout:
      orientation: 'vertical'
      Slider:
        orientation: "vertical"
        size_hint_y: 0.7        
      Label:
        size_hint_y: 0.3
        text: 'Left'
    
  Label:
    text: 'Left'
  Label:
    text: 'Left'
